ALTERNATIVE:${PN}-doc = "fsck.8 eject.1 logger.1 kill.1"
ALTERNATIVE_LINK_NAME[fsck.8] = "${mandir}/man8/fsck.8"
ALTERNATIVE_LINK_NAME[eject.1] = "${mandir}/man1/eject.1"
ALTERNATIVE_LINK_NAME[logger.1] = "${mandir}/man1/logger.1"
ALTERNATIVE_LINK_NAME[kill.1] = "${mandir}/man1/kill.1"
