#!/usr/bin/env bash

umask 022

BDIR=${BDIR:-build}
export BDIR=${BDIR}

DISTRO=${DISTRO:-freedom-u-sdk}
export DISTRO=${DISTRO}

TEMPLATECONF=${TEMPLATECONF:-freedom-u-sdk/conf}
export TEMPLATECONF=${TEMPLATECONF}

PATH="$(pwd)/freedom-u-sdk/scripts:${PATH}"

export PATH=${PATH}

source ./layers/oe-init-build-env $@
