#!/bin/bash

TOP="$(readlink -f .)"

find "${TOP}"/meta-sifive -name "*.conf" | grep conf/machine | while read cf
do
    name="$(basename "${cf}" .conf)"
    desc="$(cat "${cf}" | grep "^#@DESCRIPTION" | cut -d' ' -f2-)"

    echo -e "${name}\t${desc}"
done
