#!/bin/bash

TOP="$(readlink -f .)"

find "${TOP}"/meta-sifive -name "*.bb" | grep recipes-sifive/images | while read bb
do
    name="$(basename "${bb}" .bb)"
    desc="$(cat "${bb}" | grep ^DESCRIPTION | cut -d'"' -f2)"

    printf "%-30s %s\n" "${name}" "${desc}"
done
