#!/bin/bash

TOP="$(readlink -f .)"

find "${TOP}" -name "*.bb" | grep recipes-sifive/images | while read bb
do
    name="$(basename "${bb}" .bb)"
    desc="$(cat "${bb}" | grep ^DESCRIPTION | cut -d'"' -f2)"

    echo -e "${name}\t${desc}"
done
