#!/bin/sh

nbdrootfs_enabled() {
	if [ ${bootparam_root} != "/dev/nbd0" ] || [ -z ${bootparam_nbdroot} ]; then
		return 1
	fi
	return 0
}

nbdrootfs_run() {
	local nbd_opts
	local location
	local server_ip
	local iptype

	# ip=dhcp root=/dev/nbd0 rw nbdroot=10.0.2.2:foo nbdport=10809 console=ttySIF0,115200 earlycon=sbi
#	bootparam_nbdroot="10.0.2.2:foo"
#	bootparam_nbdport="10809"
#	bootparam_root="/dev/nbd0"
#	bootparam_ip="dhcp"
#	ROOTFS_DIR="/rootfs"

	echo "nbdroot=${bootparam_nbdroot}"
	echo "ip=${bootparam_ip}"
	echo "nbdport=${bootparam_nbdport}"

	set -x
	nbd_opts=""
	if [ "${bootparam_nbdroot#*,}" != "${bootparam_nbdroot}" ]; then
		nbd_opts="-o ${bootparam_nbdroot#*,}"
	fi

	location="${bootparam_nbdroot%%,*}"

	# echo "<location#*:>= ${location#*:}"

	if [ "${location#*:}" = "${location}" ]; then
		# server-ip not given. Get server ip from ip option
		if [ -z "$server_ip" ]; then
			fatal "Server IP is not set. Update ip or nbdroot options."
		fi
	else
		server_ip="${location%%:*}"
		location="${location#*:}"
	fi

	# echo "location=${location}"
	# echo "server_ip=${server_ip}"
	# echo "nbd-client -name ${location} ${server_ip} ${bootparam_nbdport} ${bootparam_root}"
	# echo "mount ${bootparam_root} ${ROOTFS_DIR}"

	nbd-client -name ${location} ${server_ip} ${bootparam_nbdport} ${bootparam_root}
	mount ${bootparam_root} ${ROOTFS_DIR}

	set +x
}
